---
title: "Week 1"
subtitle: "Data visualization"
description: |
  The grammar of graphics and ggplot2 API and designing effective plots
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r, include=FALSE}
  library(emo)
```

# Resource Roundup

We'll work our way through most of [*R for Data Science*](https://r4ds.had.co.nz/index.html) by Hadley Wickham and Garrett Grolemund (R4DS). You can use the free online version or order a physical copy from [Amazon](http://amzn.to/2aHLAQ1).

We'll also read several chapters in Professor Kieran Healy's book [*Data Visualization*](https://socviz.co/) (SOCVIZ). You can use the free online version or order a physical copy from [Amazon](https://www.amazon.com/gp/product/0691181624/ref=as_li_tl?ie=UTF8&tag=kieranhealysw-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=0691181624&linkId=16d53b3cc1ec3bc3aac60b27c29b92e8) (it's a beautiful book that should probably be on your bookshelf at some point).

It's important that you read the chapters AND run the code as you go. If you read without coding you are likely to trick yourself into thinking you've learned more than you have. This type of material requires most of us to be active learners. `Read/Type/Run` > `Read/Copy/Paste/Run` > `Read only`.

# Jan 11: The grammar of graphics and ggplot2 API

## Prepare

* `r emo::ji("down_arrow")`: [RStudio IDE cheatsheet](https://github.com/rstudio/cheatsheets/raw/main/rstudio-ide.pdf)
* `r emo::ji("open_book")`: [SOCVIZ Preface (Before you begin)](https://socviz.co/index.html#install)
* `r emo::ji("open_book")`: [SOCVIZ Chapter 1](https://socviz.co/lookatdata.html#lookatdata)
* `r emo::ji("open_book")`: [SOCVIZ Chapter 2](https://socviz.co/gettingstarted.html#gettingstarted)
* `r emo::ji("open_book")`: [R4DS Chapter 1](https://r4ds.had.co.nz/introduction.html)

## During Class

[Deck](https://ericpgreen.github.io/glhlth562/materials/dataviz1/dataviz1_deck.html) / Materials ([zip](https://www.dropbox.com/s/m1vkvenokyftpa9/dataviz1.zip?dl=1) or [github](https://github.com/ericpgreen/glhlth562/tree/main/materials/dataviz1))

## After Class (Optional)

* `r emo::ji("open_book")`: [ModernDive Chapter 1](https://moderndive.netlify.app/1-getting-started.html), provides a nice intro to R, RStudio, and packages if you're feeling a bit shaky.
* `r emo::ji("computer")`: {`learnr`} tutorial on [getting started with R/RStudio](https://aosmith.shinyapps.io/part1_rbasics_getting_started/)


# Jan 13: Designing effective plots

## Prepare

* `r emo::ji("tv")`: Reporting on and visualising the pandemic ([video](https://www.rstudio.com/resources/rstudioglobal-2021/reporting-on-and-visualising-the-pandemic/) 50 min)
* `r emo::ji("down_arrow")`: [Data visualization cheatsheet](https://github.com/rstudio/cheatsheets/raw/main/data-visualization-2.1.pdf)
* `r emo::ji("open_book")`: [SOCVIZ Chapter 5](https://socviz.co/workgeoms.html#workgeoms)
* `r emo::ji("open_book")`: [R4DS Chapter 3](https://r4ds.had.co.nz/data-visualisation.html)


## During Class

Deck / Materials

## After Class (Optional)

* `r emo::ji("computer")`: Tutorials: [Visualize Data](https://rstudio.cloud/learn/primers/3)

## TidyTuesday

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The <a href="https://twitter.com/R4DScommunity?ref_src=twsrc%5Etfw">@R4DScommunity</a> welcomes you to week 2 of <a href="https://twitter.com/hashtag/TidyTuesday?src=hash&amp;ref_src=twsrc%5Etfw">#TidyTuesday</a>! We&#39;re exploring Bee colony loss!<br><br>📂 <a href="https://t.co/sElb4fcv3u">https://t.co/sElb4fcv3u</a><br>🗞 <a href="https://t.co/6TiLX8FWE4">https://t.co/6TiLX8FWE4</a><a href="https://twitter.com/hashtag/r4ds?src=hash&amp;ref_src=twsrc%5Etfw">#r4ds</a> <a href="https://twitter.com/hashtag/tidyverse?src=hash&amp;ref_src=twsrc%5Etfw">#tidyverse</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> <a href="https://t.co/xY5CFgeMf9">pic.twitter.com/xY5CFgeMf9</a></p>&mdash; Tom Mock (@thomas_mock) <a href="https://twitter.com/thomas_mock/status/1480724289955454984?ref_src=twsrc%5Etfw">January 11, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Bees! [Data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-01-11/readme.md) / [Template](https://www.dropbox.com/s/i1mf75oja07985u/tidytuesday.zip?dl=1)

