---
title: "Week 4"
subtitle: "Data wrangling"
description: |
  Tidy data and relational data
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r, include=FALSE}
  library(emo)
```

# Feb 1: Tidy data

## Prepare

* `r emo::ji("down_arrow")`: [Tidying data cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/tidyr.pdf)
* `r emo::ji("open_book")`: [R4DS Chapter 12](https://r4ds.had.co.nz/tidy-data.html)
* `r emo::ji("notebook")`: Wickham, H. (2014). Tidy data. [*Journal of Statistical Software, 59(10)*, 1–23](https://doi.org/10.18637/jss.v059.i10).
* `r emo::ji("notebook")`: Broman, K., W. & Woo, K. H. (2018). Data organization in spreadsheets. *The American Statistician, 72(1)*, 2-10, DOI: [10.1080/00031305.2017.1375989](https://doi.org/10.1080/00031305.2017.1375989)
  
## During Class

[Deck](https://ericpgreen.github.io/glhlth562/materials/wrangling3_4/wrangling3.html) / Materials ([zip](https://www.dropbox.com/s/i66t7f4fqzhnk0s/wrangling3_4.zip?dl=1))

## After Class (Optional)

* `r emo::ji("studio_microphone")`: Making Data Simple podcast: [Hadley Wickham talks about his journey in data science, tidy data concepts, and his many books](https://podcasts.apple.com/fi/podcast/hadley-wickham-talks-about-his-journey-in-data-science/id605818735?i=1000485015810).

# Feb 3: Relational data

## Prepare

* `r emo::ji("open_book")`: [R4DS Chapter 13](https://r4ds.had.co.nz/relational-data.html)

## During Class

[Deck](https://ericpgreen.github.io/glhlth562/materials/wrangling3_4/wrangling4.html) / Materials ([zip](https://www.dropbox.com/s/i66t7f4fqzhnk0s/wrangling3_4.zip?dl=1))

## After Class (Optional)

* `r emo::ji("tv")`: [Using dplyr's join functions in R to filter and merge data frames](https://www.youtube.com/watch?v=jAl0fRqxK3s)

## TidyTuesday

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The <a href="https://twitter.com/R4DScommunity?ref_src=twsrc%5Etfw">@R4DScommunity</a> welcomes you to week 5 of <a href="https://twitter.com/hashtag/TidyTuesday?src=hash&amp;ref_src=twsrc%5Etfw">#TidyTuesday</a>! We&#39;re exploring dog breeds!!<br><br>📁 <a href="https://t.co/sElb4fcv3u">https://t.co/sElb4fcv3u</a><br>📰 <a href="https://t.co/EEp6maav9f">https://t.co/EEp6maav9f</a><a href="https://twitter.com/hashtag/r4ds?src=hash&amp;ref_src=twsrc%5Etfw">#r4ds</a> <a href="https://twitter.com/hashtag/tidyverse?src=hash&amp;ref_src=twsrc%5Etfw">#tidyverse</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> <a href="https://t.co/Z1hEuV8kvS">pic.twitter.com/Z1hEuV8kvS</a></p>&mdash; Tom Mock (@thomas_mock) <a href="https://twitter.com/thomas_mock/status/1488320731746385920?ref_src=twsrc%5Etfw">February 1, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
